name: Generator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
        pip install mkdocs-material
    - name: Cleanup files
      run: |
        rm -rf site
    - name: Build static files
      run: |
        mkdocs build
    - name: Building gh-pages repo
      run: |
        cd site/
        echo 'consulo.dev' > CNAME
        git init -b gh-pages
        git remote add origin git@github.com:consulo/consulo-dev.github.io.git
        git config --global user.email "consulo.bot@gmail.com"
        git config --global user.name "Consulo Bot"
        git add --all
        git commit -m "Update static files"
    - name: Pushing static files
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        directory: site
        force: true